Repository pygame-community/PygameCommunityBot, pull requests merged in 2021-06, with the labels that each got.

#341 Add unique parameter to pg!poll, make poll DB, minor PEP 8 Changes
  main.py
  pgbot/__init__.py
  pgbot/commands/admin/__init__.py
  pgbot/commands/admin/sudo.py
  pgbot/commands/user/__init__.py
  pgbot/utils/embed_utils.py
Labels: Feature Request ✋, enhancement ✨

#345 implement pg!feature, fix minor bug in pg!doc, pg!rules and dad joke
  main.py
  pgbot/__init__.py
  pgbot/commands/admin/__init__.py
  pgbot/commands/base.py
  pgbot/commands/user/__init__.py
  pgbot/commands/user/fun_commands.py
  pgbot/commands/user/help_commands.py
  pgbot/commands/utils/docs.py
  pgbot/common.py
  pgbot/emotion.py
  pgbot/routine.py
Labels: PR: Awaiting Review

#349 fix unique arg in poll, add `discord.PartialMessage` parser support
  pgbot/__init__.py
  pgbot/commands/admin/__init__.py
  pgbot/commands/admin/sudo.py
  pgbot/commands/base.py
  pgbot/commands/user/__init__.py
  pgbot/commands/user/fun_commands.py
  pgbot/commands/user/help_commands.py
  pgbot/common.py
  pgbot/emotion.py
  pgbot/routine.py
  pgbot/utils/utils.py
Labels: PR: Awaiting Review, base, code quality and cleanliness, user commands
